services:
  - type: web
    name: exam-management-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn Exam_management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: db.ebfnhtpfcerippubgkul.supabase.co
      - key: DB_PORT
        value: 5432
